### ISSUE TITLE
Do not use precompiled binary for macOS

### ISSUE THREAD

**Issue by sneurlax** [cypherstack/tor#13]
or use [Cargokit's precompiled binaries feature ](https://github.com/irondash/cargokit/blob/main/docs/precompiled_binaries.md)for better security

**Comment by sneurlax** [comment]
Resolved by https://github.com/irondash/cargokit/issues/14#issuecomment-1717947382

**Comment by julian-CStack** [comment]
https://github.com/cypherstack/tor/pull/15
